package entidades;
// Generated 17/07/2019 10:46:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiporeserva generated by hbm2java
 */
public class Tiporeserva  implements java.io.Serializable {


     private int idTipoReserva;
     private String descripcion;
     private Set reservacitas = new HashSet(0);

    public Tiporeserva() {
    }

	
    public Tiporeserva(int idTipoReserva, String descripcion) {
        this.idTipoReserva = idTipoReserva;
        this.descripcion = descripcion;
    }
    public Tiporeserva(int idTipoReserva, String descripcion, Set reservacitas) {
       this.idTipoReserva = idTipoReserva;
       this.descripcion = descripcion;
       this.reservacitas = reservacitas;
    }
   
    public int getIdTipoReserva() {
        return this.idTipoReserva;
    }
    
    public void setIdTipoReserva(int idTipoReserva) {
        this.idTipoReserva = idTipoReserva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getReservacitas() {
        return this.reservacitas;
    }
    
    public void setReservacitas(Set reservacitas) {
        this.reservacitas = reservacitas;
    }




}


